project_id = "jjllqcgywodfnaotnkxe"

[functions.guest-purchase]
verify_jwt = false

[functions.track-referral]
verify_jwt = false

[functions.verify-legacy-password]
verify_jwt = false

[functions.import-csv-tracks]
verify_jwt = false

[functions.update-audio-durations]
verify_jwt = false

[functions.download-missing-audio]
verify_jwt = false
